services:
  # uncomment this when you want to try your app in container
  # app
  # backend:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  container_name: backend
  #  restart: unless-stopped
  #  depends_on:
  #    - backend_db
  #    - backend_mq
  #    - backend_cache
  #    - backend_storage
  #  ports:
  #    - "443:443"
  #   #make sure to mount the config file to /
  #   #change to config.yaml and ENV "production" for production
  #  volumes:
  #    - ./config.yaml:/config.yaml
  #    - ./config/cert/:/config/cert/
  #  environment:
  #    - ENV=${ENV}
  #  command: "/backend"

  # db
  backend_db:
    image: postgres:18.3-alpine3.23
    container_name: backend_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - backend_db_data:/var/lib/postgresql

  # valkey
  backend_cache:
    image: valkey/valkey-bundle:9-alpine
    container_name: backend_cache
    volumes:
      - backend_valkey_data:/data
      - ./config/cache/valkey.acl:/etc/valkey/valkey.acl
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["valkey-server", "--aclfile", "/etc/valkey/valkey.acl"]

  backend_logs:
    container_name: monitoring-vlogs
    image: victoriametrics/victoria-logs:v1.50.0
    ports:
      - "9428:9428"
    command:
      - "--storageDataPath=/vlogs"
    volumes:
      - backend_logs_data:/vlogs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9428"]
      interval: 30s
      timeout: 10s
      retries: 5
      
  selfish-gateway:
    image: nginx:1.28.0-alpine-slim
    container_name: selfish-gateway
    # ports:
    #   - "8081:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert/server.crt:/etc/nginx/ssl/server.crt
      - ./cert/server.key:/etc/nginx/ssl/server.key
    restart: unless-stopped
    network_mode: "host"

  prometheus:
    image: prom/prometheus:v3.12.0-distroless
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.54.1
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      
volumes:
  backend_db_data: {}
  backend_valkey_data: {}
  backend_logs_data: {}
  prometheus_data: {}
  
