// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	UserAgent        pgtype.Text
	IpAddress        pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	Provider       string
	ProviderUserID int64
	Username       string
	Email          pgtype.Text
	AvatarUrl      pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
