// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package user_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (
  id,
  user_id,
  refresh_token_hash,
  expires_at,
  user_agent,
  ip_address,
  created_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  now(),
  now()
)
RETURNING id, user_id, refresh_token_hash, expires_at, revoked_at, user_agent, ip_address, created_at, updated_at
`

type CreateAuthSessionParams struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	UserAgent        pgtype.Text
	IpAddress        pgtype.Text
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthSessionByRefreshTokenHash = `-- name: GetAuthSessionByRefreshTokenHash :one
SELECT id, user_id, refresh_token_hash, expires_at, revoked_at, user_agent, ip_address, created_at, updated_at
FROM auth_sessions
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetAuthSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByRefreshTokenHash, refreshTokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, provider, provider_user_id, username, email, avatar_url, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAuthSessionByID = `-- name: RevokeAuthSessionByID :exec
UPDATE auth_sessions
SET revoked_at = now(),
    updated_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAuthSessionByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAuthSessionByID, id)
	return err
}

const rotateAuthSessionToken = `-- name: RotateAuthSessionToken :exec
UPDATE auth_sessions
SET refresh_token_hash = $2,
    expires_at = $3,
    updated_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

type RotateAuthSessionTokenParams struct {
	ID               pgtype.UUID
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) RotateAuthSessionToken(ctx context.Context, arg RotateAuthSessionTokenParams) error {
	_, err := q.db.Exec(ctx, rotateAuthSessionToken, arg.ID, arg.RefreshTokenHash, arg.ExpiresAt)
	return err
}

const upsertGithubUser = `-- name: UpsertGithubUser :one
INSERT INTO users (
  id,
  provider,
  provider_user_id,
  username,
  email,
  avatar_url,
  created_at,
  updated_at
) VALUES (
  $1,
  'github',
  $2,
  $3,
  $4,
  $5,
  now(),
  now()
)
ON CONFLICT (provider, provider_user_id)
DO UPDATE SET
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  avatar_url = EXCLUDED.avatar_url,
  updated_at = now()
RETURNING id, provider, provider_user_id, username, email, avatar_url, created_at, updated_at
`

type UpsertGithubUserParams struct {
	ID             pgtype.UUID
	ProviderUserID int64
	Username       string
	Email          pgtype.Text
	AvatarUrl      pgtype.Text
}

func (q *Queries) UpsertGithubUser(ctx context.Context, arg UpsertGithubUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertGithubUser,
		arg.ID,
		arg.ProviderUserID,
		arg.Username,
		arg.Email,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
