// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_app.sql

package github_app_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGithubInstallationByUserIDAndInstallationID = `-- name: DeleteGithubInstallationByUserIDAndInstallationID :exec
DELETE FROM github_installations
WHERE user_id = $1
  AND installation_id = $2
`

type DeleteGithubInstallationByUserIDAndInstallationIDParams struct {
	UserID         pgtype.UUID
	InstallationID int64
}

func (q *Queries) DeleteGithubInstallationByUserIDAndInstallationID(ctx context.Context, arg DeleteGithubInstallationByUserIDAndInstallationIDParams) error {
	_, err := q.db.Exec(ctx, deleteGithubInstallationByUserIDAndInstallationID, arg.UserID, arg.InstallationID)
	return err
}

const deleteGithubInstallationsByUserID = `-- name: DeleteGithubInstallationsByUserID :exec
DELETE FROM github_installations
WHERE user_id = $1
`

func (q *Queries) DeleteGithubInstallationsByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGithubInstallationsByUserID, userID)
	return err
}

const getGithubInstallationByUserIDAndInstallationID = `-- name: GetGithubInstallationByUserIDAndInstallationID :one
SELECT
  id,
  user_id,
  installation_id,
  account_login,
  account_id,
  target_type,
  created_at,
  updated_at
FROM github_installations
WHERE user_id = $1
  AND installation_id = $2
LIMIT 1
`

type GetGithubInstallationByUserIDAndInstallationIDParams struct {
	UserID         pgtype.UUID
	InstallationID int64
}

func (q *Queries) GetGithubInstallationByUserIDAndInstallationID(ctx context.Context, arg GetGithubInstallationByUserIDAndInstallationIDParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getGithubInstallationByUserIDAndInstallationID, arg.UserID, arg.InstallationID)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountID,
		&i.TargetType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGithubInstallationsByUserID = `-- name: ListGithubInstallationsByUserID :many
SELECT
  id,
  user_id,
  installation_id,
  account_login,
  account_id,
  target_type,
  created_at,
  updated_at
FROM github_installations
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListGithubInstallationsByUserID(ctx context.Context, userID pgtype.UUID) ([]GithubInstallation, error) {
	rows, err := q.db.Query(ctx, listGithubInstallationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubInstallation
	for rows.Next() {
		var i GithubInstallation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstallationID,
			&i.AccountLogin,
			&i.AccountID,
			&i.TargetType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGithubInstallation = `-- name: UpsertGithubInstallation :one
INSERT INTO github_installations (
  id,
  user_id,
  installation_id,
  account_login,
  account_id,
  target_type,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  now()
)
ON CONFLICT (user_id, installation_id)
DO UPDATE SET
  account_login = EXCLUDED.account_login,
  account_id = EXCLUDED.account_id,
  target_type = EXCLUDED.target_type,
  updated_at = now()
RETURNING
  id,
  user_id,
  installation_id,
  account_login,
  account_id,
  target_type,
  created_at,
  updated_at
`

type UpsertGithubInstallationParams struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	InstallationID int64
	AccountLogin   pgtype.Text
	AccountID      pgtype.Int8
	TargetType     pgtype.Text
}

func (q *Queries) UpsertGithubInstallation(ctx context.Context, arg UpsertGithubInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, upsertGithubInstallation,
		arg.ID,
		arg.UserID,
		arg.InstallationID,
		arg.AccountLogin,
		arg.AccountID,
		arg.TargetType,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountID,
		&i.TargetType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
