// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package github_app_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GithubInstallation struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	InstallationID int64
	AccountLogin   pgtype.Text
	AccountID      pgtype.Int8
	TargetType     pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	Provider       string
	ProviderUserID int64
	Username       string
	Email          pgtype.Text
	AvatarUrl      pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
