// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: container.sql

package container_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContainer = `-- name: CreateContainer :exec
INSERT INTO container (name,deployment_history_id)
VALUES ($1,$2)
`

type CreateContainerParams struct {
	Name                string
	DeploymentHistoryID int32
}

func (q *Queries) CreateContainer(ctx context.Context, arg CreateContainerParams) error {
	_, err := q.db.Exec(ctx, createContainer, arg.Name, arg.DeploymentHistoryID)
	return err
}

const getActiveDeploymentHistoryContainerByDeploymentId = `-- name: GetActiveDeploymentHistoryContainerByDeploymentId :one
SELECT
  c.id, c.name, c.deployment_history_id, c.created_at, c.updated_at
FROM container c
JOIN deployment_history dh
  ON dh.id = c.deployment_history_id
WHERE
  dh.deployment_id = $1
`

func (q *Queries) GetActiveDeploymentHistoryContainerByDeploymentId(ctx context.Context, deploymentID pgtype.UUID) (Container, error) {
	row := q.db.QueryRow(ctx, getActiveDeploymentHistoryContainerByDeploymentId, deploymentID)
	var i Container
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeploymentHistoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
