// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package container_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Container struct {
	ID                  pgtype.UUID
	Name                string
	DeploymentHistoryID int32
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type Deployment struct {
	ID        pgtype.UUID
	Name      string
	ProjectID pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type DeploymentHistory struct {
	ID                    int32
	DeploymentID          pgtype.UUID
	GitRemoteUrl          string
	Branch                string
	CommitID              string
	CommitMsg             string
	Version               string
	ExternalPort          []int32
	DeploymentTechstackID int32
	BuildCommand          pgtype.Text
	BuildFolder           pgtype.Text
	RunCommand            pgtype.Text
	IsActive              bool
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type DeploymentTechstack struct {
	ID                 int32
	Name               string
	Version            string
	DockerBaseImage    string
	DockerRuntimeImage string
}

type GithubInstallation struct {
	ID             int32
	InstallationID int64
	CreatedAt      pgtype.Timestamptz
}

type Project struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
