// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment.sql

package deployment_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployment = `-- name: CreateDeployment :exec
INSERT INTO public.deployment (name,git_remote_url,project_id,installation_id)
VALUES ($1,$2,$3,$4)
`

type CreateDeploymentParams struct {
	Name           string
	GitRemoteUrl   string
	ProjectID      pgtype.UUID
	InstallationID int64
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) error {
	_, err := q.db.Exec(ctx, createDeployment,
		arg.Name,
		arg.GitRemoteUrl,
		arg.ProjectID,
		arg.InstallationID,
	)
	return err
}

const createDeploymentHistory = `-- name: CreateDeploymentHistory :one
INSERT INTO public.deployment_history (deployment_id, branch, commit_id, commit_msg, version, external_port, deployment_techstack_id, build_command, build_folder, run_command)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id
`

type CreateDeploymentHistoryParams struct {
	DeploymentID          pgtype.UUID
	Branch                string
	CommitID              string
	CommitMsg             string
	Version               string
	ExternalPort          []int32
	DeploymentTechstackID int32
	BuildCommand          pgtype.Text
	BuildFolder           pgtype.Text
	RunCommand            pgtype.Text
}

func (q *Queries) CreateDeploymentHistory(ctx context.Context, arg CreateDeploymentHistoryParams) (int32, error) {
	row := q.db.QueryRow(ctx, createDeploymentHistory,
		arg.DeploymentID,
		arg.Branch,
		arg.CommitID,
		arg.CommitMsg,
		arg.Version,
		arg.ExternalPort,
		arg.DeploymentTechstackID,
		arg.BuildCommand,
		arg.BuildFolder,
		arg.RunCommand,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteDeploymentByDeploymentId = `-- name: DeleteDeploymentByDeploymentId :exec
DELETE FROM
  deployment d
USING project p
WHERE
  p.id = d.project_id
  AND p.user_id = $1
  AND d.id = $2
`

type DeleteDeploymentByDeploymentIdParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) DeleteDeploymentByDeploymentId(ctx context.Context, arg DeleteDeploymentByDeploymentIdParams) error {
	_, err := q.db.Exec(ctx, deleteDeploymentByDeploymentId, arg.UserID, arg.ID)
	return err
}

const getActiveDeploymentHistoryByDeploymentId = `-- name: GetActiveDeploymentHistoryByDeploymentId :one
SELECT
  dh.id AS deployment_history_id,
  dh.branch AS branch,
  dh.commit_id AS commit_id,
  dh.commit_msg AS commit_message,
  dh.version AS deployment_version,
  dh.external_port AS port,
  dh.build_command AS build_command,
  dt.id AS techstack_id,
  dt.name AS techstack_name,
  dt.version AS techstack_version
FROM deployment_history dh
JOIN deployment d
  ON dh.deployment_id = d.id
JOIN project p
  ON d.project_id = p.id
JOIN deployment_techstack dt
  ON dh.deployment_techstack_id = dt.id
WHERE
  p.user_id = $1
  AND dh.deployment_id = $2
  AND dh.is_active = true
`

type GetActiveDeploymentHistoryByDeploymentIdParams struct {
	UserID       pgtype.UUID
	DeploymentID pgtype.UUID
}

type GetActiveDeploymentHistoryByDeploymentIdRow struct {
	DeploymentHistoryID int32
	Branch              string
	CommitID            string
	CommitMessage       string
	DeploymentVersion   string
	Port                []int32
	BuildCommand        pgtype.Text
	TechstackID         int32
	TechstackName       string
	TechstackVersion    string
}

func (q *Queries) GetActiveDeploymentHistoryByDeploymentId(ctx context.Context, arg GetActiveDeploymentHistoryByDeploymentIdParams) (GetActiveDeploymentHistoryByDeploymentIdRow, error) {
	row := q.db.QueryRow(ctx, getActiveDeploymentHistoryByDeploymentId, arg.UserID, arg.DeploymentID)
	var i GetActiveDeploymentHistoryByDeploymentIdRow
	err := row.Scan(
		&i.DeploymentHistoryID,
		&i.Branch,
		&i.CommitID,
		&i.CommitMessage,
		&i.DeploymentVersion,
		&i.Port,
		&i.BuildCommand,
		&i.TechstackID,
		&i.TechstackName,
		&i.TechstackVersion,
	)
	return i, err
}

const getDeploymentByDeploymentId = `-- name: GetDeploymentByDeploymentId :one
SELECT
  d.id, d.name, d.git_remote_url, d.project_id, d.installation_id, d.created_at, d.updated_at
FROM deployment d
JOIN project p
  ON p.id = d.project_id
WHERE
  p.user_id = $1
  AND d.id = $2
`

type GetDeploymentByDeploymentIdParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) GetDeploymentByDeploymentId(ctx context.Context, arg GetDeploymentByDeploymentIdParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentByDeploymentId, arg.UserID, arg.ID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GitRemoteUrl,
		&i.ProjectID,
		&i.InstallationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeploymentHistoryByDeploymentId = `-- name: GetDeploymentHistoryByDeploymentId :many
SELECT
  dh.id,
  dh.branch,
  dh.commit_id,
  dh.commit_msg AS commit_message,
  dh.version AS deployment_version,
  dh.external_port AS port,
  dh.created_at,
  dh.updated_at
FROM deployment_history dh
JOIN deployment d
  ON dh.deployment_id = d.id
JOIN project p
  ON d.project_id = p.id
WHERE
  p.user_id = $1 AND
  dh.deployment_id = $2 AND
  dh.is_active = false
ORDER BY
  COALESCE(dh.updated_at, dh.created_at) DESC
`

type GetDeploymentHistoryByDeploymentIdParams struct {
	UserID       pgtype.UUID
	DeploymentID pgtype.UUID
}

type GetDeploymentHistoryByDeploymentIdRow struct {
	ID                int32
	Branch            string
	CommitID          string
	CommitMessage     string
	DeploymentVersion string
	Port              []int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetDeploymentHistoryByDeploymentId(ctx context.Context, arg GetDeploymentHistoryByDeploymentIdParams) ([]GetDeploymentHistoryByDeploymentIdRow, error) {
	rows, err := q.db.Query(ctx, getDeploymentHistoryByDeploymentId, arg.UserID, arg.DeploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentHistoryByDeploymentIdRow
	for rows.Next() {
		var i GetDeploymentHistoryByDeploymentIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Branch,
			&i.CommitID,
			&i.CommitMessage,
			&i.DeploymentVersion,
			&i.Port,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeploymentsByProjectId = `-- name: GetDeploymentsByProjectId :many
SELECT
  CAST (d.id AS VARCHAR) AS deployment_id,
  d.name AS deployment_name,
  d.git_remote_url as git_remote_url,
  CAST (dh.branch AS VARCHAR) AS branch,
  CAST (dh.commit_id AS VARCHAR) AS commit_id,
  CAST (dh.commit_msg AS VARCHAR) AS commit_message,
  CAST (dh.version AS VARCHAR) AS deployment_version,
  dh.external_port AS port,
  dt.name AS techstack_name,
  dt.version AS techstack_version,
  CAST (c.id AS VARCHAR) AS container_id,
  dh.created_at AS created_at,
  dh.updated_at AS updated_at
FROM
  deployment d
JOIN project p
  ON p.id = d.project_id
LEFT JOIN deployment_history dh
  ON d.id = dh.deployment_id
JOIN deployment_techstack dt
  ON dh.deployment_techstack_id = dt.id
LEFT JOIN container c
  ON c.deployment_history_id = dh.id
WHERE
  p.user_id = $1
  AND d.project_id = $2
  AND dh.is_active = true
`

type GetDeploymentsByProjectIdParams struct {
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
}

type GetDeploymentsByProjectIdRow struct {
	DeploymentID      string
	DeploymentName    string
	GitRemoteUrl      string
	Branch            string
	CommitID          string
	CommitMessage     string
	DeploymentVersion string
	Port              []int32
	TechstackName     string
	TechstackVersion  string
	ContainerID       string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetDeploymentsByProjectId(ctx context.Context, arg GetDeploymentsByProjectIdParams) ([]GetDeploymentsByProjectIdRow, error) {
	rows, err := q.db.Query(ctx, getDeploymentsByProjectId, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentsByProjectIdRow
	for rows.Next() {
		var i GetDeploymentsByProjectIdRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.DeploymentName,
			&i.GitRemoteUrl,
			&i.Branch,
			&i.CommitID,
			&i.CommitMessage,
			&i.DeploymentVersion,
			&i.Port,
			&i.TechstackName,
			&i.TechstackVersion,
			&i.ContainerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByDeploymentId = `-- name: GetProjectByDeploymentId :one
SELECT
  p.id, p.user_id, p.name, p.description, p.created_at, p.updated_at
FROM deployment d
JOIN project p
  ON d.project_id = p.id
WHERE
  p.user_id = $1
  AND d.id = $2
`

type GetProjectByDeploymentIdParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) GetProjectByDeploymentId(ctx context.Context, arg GetProjectByDeploymentIdParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByDeploymentId, arg.UserID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTechstackByTechstackId = `-- name: GetTechstackByTechstackId :one
SELECT
  id, name, version, docker_base_image, docker_runtime_image, created_at, updated_at
FROM deployment_techstack dt
WHERE
  id = $1
`

func (q *Queries) GetTechstackByTechstackId(ctx context.Context, id int32) (DeploymentTechstack, error) {
	row := q.db.QueryRow(ctx, getTechstackByTechstackId, id)
	var i DeploymentTechstack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.DockerBaseImage,
		&i.DockerRuntimeImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setActiveDeploymentHistoryNonActiveByDeploymentId = `-- name: SetActiveDeploymentHistoryNonActiveByDeploymentId :exec
UPDATE deployment_history dh
SET is_active = false
FROM deployment d
JOIN project p
  ON p.id = d.project_id
WHERE
  d.id = dh.deployment_id
  AND p.user_id = $1
  AND dh.deployment_id = $2
  AND dh.is_active = true
`

type SetActiveDeploymentHistoryNonActiveByDeploymentIdParams struct {
	UserID       pgtype.UUID
	DeploymentID pgtype.UUID
}

func (q *Queries) SetActiveDeploymentHistoryNonActiveByDeploymentId(ctx context.Context, arg SetActiveDeploymentHistoryNonActiveByDeploymentIdParams) error {
	_, err := q.db.Exec(ctx, setActiveDeploymentHistoryNonActiveByDeploymentId, arg.UserID, arg.DeploymentID)
	return err
}

const setNonActiveDeploymentHistoryActiveByDeploymentHistoryId = `-- name: SetNonActiveDeploymentHistoryActiveByDeploymentHistoryId :exec
UPDATE deployment_history dh
SET is_active = true
FROM deployment d
JOIN project p
  ON p.id = d.project_id
WHERE
  d.id = dh.deployment_id
  AND p.user_id = $1
  AND dh.id = $2
  AND dh.is_active = false
`

type SetNonActiveDeploymentHistoryActiveByDeploymentHistoryIdParams struct {
	UserID pgtype.UUID
	ID     int32
}

func (q *Queries) SetNonActiveDeploymentHistoryActiveByDeploymentHistoryId(ctx context.Context, arg SetNonActiveDeploymentHistoryActiveByDeploymentHistoryIdParams) error {
	_, err := q.db.Exec(ctx, setNonActiveDeploymentHistoryActiveByDeploymentHistoryId, arg.UserID, arg.ID)
	return err
}
