// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment.sql

package deployment_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeploymentHistory = `-- name: CreateDeploymentHistory :one
INSERT INTO public.deployment_history (deployment_id, branch, commit_id, commit_msg, version, deployment_techstack_id, build_command, build_folder, run_command, main_file_path)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id
`

type CreateDeploymentHistoryParams struct {
	DeploymentID          pgtype.UUID
	Branch                string
	CommitID              string
	CommitMsg             string
	Version               string
	DeploymentTechstackID int32
	BuildCommand          pgtype.Text
	BuildFolder           pgtype.Text
	RunCommand            pgtype.Text
	MainFilePath          pgtype.Text
}

func (q *Queries) CreateDeploymentHistory(ctx context.Context, arg CreateDeploymentHistoryParams) (int32, error) {
	row := q.db.QueryRow(ctx, createDeploymentHistory,
		arg.DeploymentID,
		arg.Branch,
		arg.CommitID,
		arg.CommitMsg,
		arg.Version,
		arg.DeploymentTechstackID,
		arg.BuildCommand,
		arg.BuildFolder,
		arg.RunCommand,
		arg.MainFilePath,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteDeploymentByDeploymentId = `-- name: DeleteDeploymentByDeploymentId :exec
DELETE FROM
  deployment d
USING project p
WHERE
  p.id = d.project_id
  AND p.user_id = $1
  AND d.id = $2
`

type DeleteDeploymentByDeploymentIdParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) DeleteDeploymentByDeploymentId(ctx context.Context, arg DeleteDeploymentByDeploymentIdParams) error {
	_, err := q.db.Exec(ctx, deleteDeploymentByDeploymentId, arg.UserID, arg.ID)
	return err
}

const deleteDeploymentByDeploymentName = `-- name: DeleteDeploymentByDeploymentName :exec
DELETE FROM
  deployment d
USING project p
WHERE
  p.user_id = $1
  AND p.name = $2
  AND d.name = $3
`

type DeleteDeploymentByDeploymentNameParams struct {
	UserID pgtype.UUID
	Name   string
	Name_2 string
}

func (q *Queries) DeleteDeploymentByDeploymentName(ctx context.Context, arg DeleteDeploymentByDeploymentNameParams) error {
	_, err := q.db.Exec(ctx, deleteDeploymentByDeploymentName, arg.UserID, arg.Name, arg.Name_2)
	return err
}

const getActiveDeploymentDetailByDeploymentName = `-- name: GetActiveDeploymentDetailByDeploymentName :one
SELECT
  p.name as project_name,
  d.id,
  d.name as deployment_name,
  d.description as deployment_description,
  d.repository_id,
  d.git_remote_url,
  d.installation_id,
  dh.branch,
  dh.version,
  dh.commit_id,
  dh.build_command,
  dh.build_folder,
  dh.run_command,
  dh.main_file_path,
  dt.id as techstack_id,
  dt.name as techstack_name,
  dt.docker_base_image,
  dt.docker_runtime_image,
  c.name as container_name,
  COALESCE(
    json_agg(
      DISTINCT jsonb_build_object(
        'key', ce.key,
        'value', ce.value
      )
    ) FILTER (WHERE ce.key IS NOT NULL), '[]'
  )::jsonb as env,
  COALESCE(
    json_agg(
      DISTINCT jsonb_build_object(
        'external', cp.external,
        'internal', cp.internal,
        'protocol', cp.protocol
      )
    ) FILTER (WHERE cp.external IS NOT NULL), '[]'
  )::jsonb as port
FROM deployment_history dh
JOIN deployment d
  ON dh.deployment_id = d.id
JOIN project p
  ON d.project_id = p.id
JOIN deployment_techstack dt
  ON dh.deployment_techstack_id = dt.id
JOIN container c
  ON c.deployment_history_id = dh.id
LEFT JOIN container_env ce
  ON ce.container_id = c.id
LEFT JOIN container_port cp
  ON cp.container_id = c.id
WHERE
  p.user_id = $1
  AND p.name ILIKE $2
  AND d.name ILIKE $3
  AND dh.is_active = true
GROUP BY
  p.id,
  d.id,
  dh.id,
  dt.id,
  c.id
ORDER BY
  COALESCE(dh.updated_at, dh.created_at) DESC
`

type GetActiveDeploymentDetailByDeploymentNameParams struct {
	UserID pgtype.UUID
	Name   string
	Name_2 string
}

type GetActiveDeploymentDetailByDeploymentNameRow struct {
	ProjectName           string
	ID                    pgtype.UUID
	DeploymentName        string
	DeploymentDescription pgtype.Text
	RepositoryID          int32
	GitRemoteUrl          string
	InstallationID        int64
	Branch                string
	Version               string
	CommitID              string
	BuildCommand          pgtype.Text
	BuildFolder           pgtype.Text
	RunCommand            pgtype.Text
	MainFilePath          pgtype.Text
	TechstackID           int32
	TechstackName         string
	DockerBaseImage       string
	DockerRuntimeImage    string
	ContainerName         string
	Env                   []byte
	Port                  []byte
}

func (q *Queries) GetActiveDeploymentDetailByDeploymentName(ctx context.Context, arg GetActiveDeploymentDetailByDeploymentNameParams) (GetActiveDeploymentDetailByDeploymentNameRow, error) {
	row := q.db.QueryRow(ctx, getActiveDeploymentDetailByDeploymentName, arg.UserID, arg.Name, arg.Name_2)
	var i GetActiveDeploymentDetailByDeploymentNameRow
	err := row.Scan(
		&i.ProjectName,
		&i.ID,
		&i.DeploymentName,
		&i.DeploymentDescription,
		&i.RepositoryID,
		&i.GitRemoteUrl,
		&i.InstallationID,
		&i.Branch,
		&i.Version,
		&i.CommitID,
		&i.BuildCommand,
		&i.BuildFolder,
		&i.RunCommand,
		&i.MainFilePath,
		&i.TechstackID,
		&i.TechstackName,
		&i.DockerBaseImage,
		&i.DockerRuntimeImage,
		&i.ContainerName,
		&i.Env,
		&i.Port,
	)
	return i, err
}

const getActiveDeploymentHistoryByDeploymentName = `-- name: GetActiveDeploymentHistoryByDeploymentName :one
SELECT
  gi.account_login as github_account,
  d.name as deployment_name,
  d.description as deployment_description,
  d.installation_id as installation_id,
  d.git_remote_url AS remote_url,
  dh.id AS deployment_history_id,
  dh.branch AS branch,
  dh.commit_id AS commit_id,
  dh.commit_msg AS commit_message,
  dh.version AS deployment_version,
  COALESCE(
    json_agg(
      DISTINCT jsonb_build_object(
        'key', ce.key,
        'value', ce.value
      )
    ) FILTER (WHERE ce.key IS NOT NULL), '[]'
  )::jsonb as env,
  COALESCE(
    json_agg(
      DISTINCT jsonb_build_object(
        'external', cp.external,
        'internal', cp.internal,
        'protocol', cp.protocol
      )
    ) FILTER (WHERE cp.external IS NOT NULL), '[]'
  )::jsonb as port,
  dh.build_command AS build_command,
  dh.build_folder AS build_folder,
  dh.main_file_path as main_file_path,
  dt.id AS techstack_id,
  dt.name AS techstack_name,
  dt.version AS techstack_version,
  c.name as container_name,
  dh.created_at,
  d.updated_at as deployment_updated_at,
  dh.updated_at
FROM deployment_history dh
JOIN container c
  ON c.deployment_history_id = dh.id
LEFT JOIN container_port cp
  ON cp.container_id = c.id
LEFT JOIN container_env ce
  ON ce.container_id = c.id
JOIN deployment d
  ON dh.deployment_id = d.id
JOIN project p
  ON d.project_id = p.id
JOIN deployment_techstack dt
  ON dh.deployment_techstack_id = dt.id
JOIN github_installations gi
  ON d.installation_id = gi.installation_id
WHERE
  p.user_id = $1
  AND p.name ILIKE $2
  AND d.name ILIKE $3
  AND dh.is_active = true
GROUP BY
  d.id,
  dh.id,
  dt.id,
  gi.id,
  c.name
`

type GetActiveDeploymentHistoryByDeploymentNameParams struct {
	UserID pgtype.UUID
	Name   string
	Name_2 string
}

type GetActiveDeploymentHistoryByDeploymentNameRow struct {
	GithubAccount         pgtype.Text
	DeploymentName        string
	DeploymentDescription pgtype.Text
	InstallationID        int64
	RemoteUrl             string
	DeploymentHistoryID   int32
	Branch                string
	CommitID              string
	CommitMessage         string
	DeploymentVersion     string
	Env                   []byte
	Port                  []byte
	BuildCommand          pgtype.Text
	BuildFolder           pgtype.Text
	MainFilePath          pgtype.Text
	TechstackID           int32
	TechstackName         string
	TechstackVersion      string
	ContainerName         string
	CreatedAt             pgtype.Timestamptz
	DeploymentUpdatedAt   pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) GetActiveDeploymentHistoryByDeploymentName(ctx context.Context, arg GetActiveDeploymentHistoryByDeploymentNameParams) (GetActiveDeploymentHistoryByDeploymentNameRow, error) {
	row := q.db.QueryRow(ctx, getActiveDeploymentHistoryByDeploymentName, arg.UserID, arg.Name, arg.Name_2)
	var i GetActiveDeploymentHistoryByDeploymentNameRow
	err := row.Scan(
		&i.GithubAccount,
		&i.DeploymentName,
		&i.DeploymentDescription,
		&i.InstallationID,
		&i.RemoteUrl,
		&i.DeploymentHistoryID,
		&i.Branch,
		&i.CommitID,
		&i.CommitMessage,
		&i.DeploymentVersion,
		&i.Env,
		&i.Port,
		&i.BuildCommand,
		&i.BuildFolder,
		&i.MainFilePath,
		&i.TechstackID,
		&i.TechstackName,
		&i.TechstackVersion,
		&i.ContainerName,
		&i.CreatedAt,
		&i.DeploymentUpdatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeploymentByDeploymentId = `-- name: GetDeploymentByDeploymentId :one
SELECT
  d.id, d.name, d.description, d.git_remote_url, d.project_id, d.installation_id, d.repository_id, d.created_at, d.updated_at
FROM deployment d
JOIN project p
  ON p.id = d.project_id
WHERE
  p.user_id = $1
  AND d.id = $2
`

type GetDeploymentByDeploymentIdParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) GetDeploymentByDeploymentId(ctx context.Context, arg GetDeploymentByDeploymentIdParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentByDeploymentId, arg.UserID, arg.ID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GitRemoteUrl,
		&i.ProjectID,
		&i.InstallationID,
		&i.RepositoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeploymentHistoryByDeploymentName = `-- name: GetDeploymentHistoryByDeploymentName :many
SELECT
  dh.id,
  dh.branch,
  dh.commit_id,
  dh.commit_msg AS commit_message,
  dh.version AS deployment_version,
  dh.build_command AS build_command,
  dt.id AS techstack_id,
  dt.name AS techstack_name,
  dt.version AS techstack_version,
  dh.created_at,
  dh.updated_at
FROM deployment_history dh
JOIN deployment d
  ON dh.deployment_id = d.id
JOIN project p
  ON d.project_id = p.id
JOIN deployment_techstack dt
  ON dh.deployment_techstack_id = dt.id
WHERE
  p.user_id = $1
  AND p.name ILIKE $2
  AND d.name ILIKE $3
  AND dh.is_active = false
GROUP BY
  dh.id,
  dh.branch,
  dh.commit_id,
  dh.commit_msg,
  dh.version,
  dh.build_command,
  dt.id,
  dt.name,
  dt.version,
  dh.created_at,
  dh.updated_at
ORDER BY
  COALESCE(dh.updated_at, dh.created_at) DESC
`

type GetDeploymentHistoryByDeploymentNameParams struct {
	UserID pgtype.UUID
	Name   string
	Name_2 string
}

type GetDeploymentHistoryByDeploymentNameRow struct {
	ID                int32
	Branch            string
	CommitID          string
	CommitMessage     string
	DeploymentVersion string
	BuildCommand      pgtype.Text
	TechstackID       int32
	TechstackName     string
	TechstackVersion  string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetDeploymentHistoryByDeploymentName(ctx context.Context, arg GetDeploymentHistoryByDeploymentNameParams) ([]GetDeploymentHistoryByDeploymentNameRow, error) {
	rows, err := q.db.Query(ctx, getDeploymentHistoryByDeploymentName, arg.UserID, arg.Name, arg.Name_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentHistoryByDeploymentNameRow
	for rows.Next() {
		var i GetDeploymentHistoryByDeploymentNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Branch,
			&i.CommitID,
			&i.CommitMessage,
			&i.DeploymentVersion,
			&i.BuildCommand,
			&i.TechstackID,
			&i.TechstackName,
			&i.TechstackVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeploymentHistoryCountByCommitID = `-- name: GetDeploymentHistoryCountByCommitID :one
SELECT
  count(*)
FROM deployment_history dh
JOIN deployment d
  ON d.id = dh.deployment_id
WHERE
  d.id = $1
  AND dh.commit_id = $2
`

type GetDeploymentHistoryCountByCommitIDParams struct {
	ID       pgtype.UUID
	CommitID string
}

func (q *Queries) GetDeploymentHistoryCountByCommitID(ctx context.Context, arg GetDeploymentHistoryCountByCommitIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getDeploymentHistoryCountByCommitID, arg.ID, arg.CommitID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDeploymentsByProjectId = `-- name: GetDeploymentsByProjectId :many
SELECT
  CAST (d.id AS VARCHAR) AS deployment_id,
  d.name AS deployment_name,
  d.git_remote_url as git_remote_url,
  CAST (dh.branch AS VARCHAR) AS branch,
  CAST (dh.commit_id AS VARCHAR) AS commit_id,
  CAST (dh.commit_msg AS VARCHAR) AS commit_message,
  CAST (dh.version AS VARCHAR) AS deployment_version,
  COALESCE(
    json_agg(
      DISTINCT jsonb_build_object(
        'external', cp.external,
        'internal', cp.internal,
        'protocol', cp.protocol
      )
    ) FILTER (WHERE cp.external IS NOT NULL), '[]'
  )::jsonb as port,
  dt.name AS techstack_name,
  dt.version AS techstack_version,
  CAST (c.id AS VARCHAR) AS container_id,
  dh.created_at AS created_at,
  dh.updated_at AS updated_at
FROM
  deployment d
JOIN project p
  ON p.id = d.project_id
LEFT JOIN deployment_history dh
  ON d.id = dh.deployment_id
JOIN deployment_techstack dt
  ON dh.deployment_techstack_id = dt.id
LEFT JOIN container c
  ON c.deployment_history_id = dh.id
LEFT JOIN container_port cp
  ON cp.container_id = c.id
WHERE
  p.user_id = $1
  AND d.project_id = $2
  AND dh.is_active = true
GROUP BY
  deployment_id
`

type GetDeploymentsByProjectIdParams struct {
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
}

type GetDeploymentsByProjectIdRow struct {
	DeploymentID      string
	DeploymentName    string
	GitRemoteUrl      string
	Branch            string
	CommitID          string
	CommitMessage     string
	DeploymentVersion string
	Port              []byte
	TechstackName     string
	TechstackVersion  string
	ContainerID       string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetDeploymentsByProjectId(ctx context.Context, arg GetDeploymentsByProjectIdParams) ([]GetDeploymentsByProjectIdRow, error) {
	rows, err := q.db.Query(ctx, getDeploymentsByProjectId, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentsByProjectIdRow
	for rows.Next() {
		var i GetDeploymentsByProjectIdRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.DeploymentName,
			&i.GitRemoteUrl,
			&i.Branch,
			&i.CommitID,
			&i.CommitMessage,
			&i.DeploymentVersion,
			&i.Port,
			&i.TechstackName,
			&i.TechstackVersion,
			&i.ContainerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByDeploymentId = `-- name: GetProjectByDeploymentId :one
SELECT
  p.id, p.user_id, p.name, p.description, p.created_at, p.updated_at
FROM deployment d
JOIN project p
  ON d.project_id = p.id
WHERE
  p.user_id = $1
  AND d.id = $2
`

type GetProjectByDeploymentIdParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) GetProjectByDeploymentId(ctx context.Context, arg GetProjectByDeploymentIdParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByDeploymentId, arg.UserID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTechstackByTechstackId = `-- name: GetTechstackByTechstackId :one
SELECT
  id, name, version, docker_base_image, docker_runtime_image, created_at, updated_at
FROM deployment_techstack dt
WHERE
  id = $1
`

func (q *Queries) GetTechstackByTechstackId(ctx context.Context, id int32) (DeploymentTechstack, error) {
	row := q.db.QueryRow(ctx, getTechstackByTechstackId, id)
	var i DeploymentTechstack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.DockerBaseImage,
		&i.DockerRuntimeImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTechstackName = `-- name: GetTechstackName :many
SELECT DISTINCT ON (LOWER(name))
  name
FROM deployment_techstack
`

func (q *Queries) GetTechstackName(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getTechstackName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTechstackVersionByName = `-- name: GetTechstackVersionByName :many
SELECT
  dt.id AS id,
  dt.VERSION AS version
FROM deployment_techstack dt
WHERE
  LOWER(dt."name") = $1
ORDER BY
  split_part(version, '.', 1)::int DESC,
  split_part(version, '.', 2)::int DESC,
  split_part(version, '.', 3)::int DESC
`

type GetTechstackVersionByNameRow struct {
	ID      int32
	Version string
}

func (q *Queries) GetTechstackVersionByName(ctx context.Context, name string) ([]GetTechstackVersionByNameRow, error) {
	rows, err := q.db.Query(ctx, getTechstackVersionByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTechstackVersionByNameRow
	for rows.Next() {
		var i GetTechstackVersionByNameRow
		if err := rows.Scan(&i.ID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveDeploymentHistoryNonActiveByDeploymentId = `-- name: SetActiveDeploymentHistoryNonActiveByDeploymentId :exec
UPDATE deployment_history dh
SET is_active = false
FROM deployment d
JOIN project p
  ON p.id = d.project_id
WHERE
  d.id = dh.deployment_id
  AND p.user_id = $1
  AND dh.deployment_id = $2
  AND dh.is_active = true
`

type SetActiveDeploymentHistoryNonActiveByDeploymentIdParams struct {
	UserID       pgtype.UUID
	DeploymentID pgtype.UUID
}

func (q *Queries) SetActiveDeploymentHistoryNonActiveByDeploymentId(ctx context.Context, arg SetActiveDeploymentHistoryNonActiveByDeploymentIdParams) error {
	_, err := q.db.Exec(ctx, setActiveDeploymentHistoryNonActiveByDeploymentId, arg.UserID, arg.DeploymentID)
	return err
}

const setNonActiveDeploymentHistoryActiveByDeploymentHistoryId = `-- name: SetNonActiveDeploymentHistoryActiveByDeploymentHistoryId :exec
UPDATE deployment_history dh
SET is_active = true
FROM deployment d
JOIN project p
  ON p.id = d.project_id
WHERE
  d.id = dh.deployment_id
  AND p.user_id = $1
  AND dh.id = $2
  AND dh.is_active = false
`

type SetNonActiveDeploymentHistoryActiveByDeploymentHistoryIdParams struct {
	UserID pgtype.UUID
	ID     int32
}

func (q *Queries) SetNonActiveDeploymentHistoryActiveByDeploymentHistoryId(ctx context.Context, arg SetNonActiveDeploymentHistoryActiveByDeploymentHistoryIdParams) error {
	_, err := q.db.Exec(ctx, setNonActiveDeploymentHistoryActiveByDeploymentHistoryId, arg.UserID, arg.ID)
	return err
}

const updateDeploymentDescriptionByDeploymentId = `-- name: UpdateDeploymentDescriptionByDeploymentId :exec
UPDATE deployment d
SET description = $3
FROM project p
WHERE
  p.id = d.project_id
  AND p.user_id = $1
  AND d.id = $2
`

type UpdateDeploymentDescriptionByDeploymentIdParams struct {
	UserID      pgtype.UUID
	ID          pgtype.UUID
	Description pgtype.Text
}

func (q *Queries) UpdateDeploymentDescriptionByDeploymentId(ctx context.Context, arg UpdateDeploymentDescriptionByDeploymentIdParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentDescriptionByDeploymentId, arg.UserID, arg.ID, arg.Description)
	return err
}

const upsertDeployment = `-- name: UpsertDeployment :one
INSERT INTO deployment (
    name,
    git_remote_url,
    project_id,
    installation_id,
    repository_id
)
SELECT
    $1,
    $2,
    p.id,
    $3,
    $4
FROM project p
WHERE p.name = $5
  AND p.user_id = $6
ON CONFLICT (name, project_id)
DO UPDATE
SET name = deployment.name
RETURNING id
`

type UpsertDeploymentParams struct {
	Name           string
	GitRemoteUrl   string
	InstallationID int64
	RepositoryID   int32
	Name_2         string
	UserID         pgtype.UUID
}

func (q *Queries) UpsertDeployment(ctx context.Context, arg UpsertDeploymentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertDeployment,
		arg.Name,
		arg.GitRemoteUrl,
		arg.InstallationID,
		arg.RepositoryID,
		arg.Name_2,
		arg.UserID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
