// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package deployment_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	UserAgent        pgtype.Text
	IpAddress        pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Container struct {
	ID                  pgtype.UUID
	Name                string
	DeploymentHistoryID int32
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type ContainerEnv struct {
	ID        int32
	Key       string
	Value     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Deployment struct {
	ID        pgtype.UUID
	Name      string
	ProjectID pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type DeploymentHistory struct {
	ID                    int32
	DeploymentID          pgtype.UUID
	GitRemoteUrl          string
	Branch                string
	CommitID              string
	CommitMsg             string
	Version               string
	ExternalPort          []int32
	DeploymentTechstackID int32
	BuildCommand          pgtype.Text
	BuildFolder           pgtype.Text
	RunCommand            pgtype.Text
	IsActive              bool
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type DeploymentTechstack struct {
	ID                 int32
	Name               string
	Version            string
	DockerBaseImage    string
	DockerRuntimeImage string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type Project struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	Provider       string
	ProviderUserID int64
	Username       string
	Email          pgtype.Text
	AvatarUrl      pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
