// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package project_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	Provider       string
	ProviderUserID int64
	Username       string
	Email          pgtype.Text
	AvatarUrl      pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
