// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package project_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :exec
INSERT INTO public.project (id,name,description)
VALUES ($1,$2,$3)
`

type CreateProjectParams struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject, arg.ID, arg.Name, arg.Description)
	return err
}

const deleteProjectById = `-- name: DeleteProjectById :exec
DELETE FROM public.project
where id = $1
`

func (q *Queries) DeleteProjectById(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectById, id)
	return err
}

const getAllProjects = `-- name: GetAllProjects :many
SELECT
  id, name, description, created_at, updated_at
FROM public.project p
`

func (q *Queries) GetAllProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, getAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectById = `-- name: GetProjectById :one
SELECT
  id, name, description, created_at, updated_at
FROM
  public.project p
WHERE
  p.id = $1
`

func (q *Queries) GetProjectById(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectById, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectById = `-- name: UpdateProjectById :exec
UPDATE public.project
SET name = $1,
    description = $2,
    updated_at = now()
WHERE id = $3
`

type UpdateProjectByIdParams struct {
	Name        string
	Description pgtype.Text
	ID          pgtype.UUID
}

func (q *Queries) UpdateProjectById(ctx context.Context, arg UpdateProjectByIdParams) error {
	_, err := q.db.Exec(ctx, updateProjectById, arg.Name, arg.Description, arg.ID)
	return err
}
