// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package project_repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :exec
INSERT INTO public.project (user_id,name,description)
VALUES ($1,$2,$3)
`

type CreateProjectParams struct {
	UserID      pgtype.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject, arg.UserID, arg.Name, arg.Description)
	return err
}

const deleteProjectById = `-- name: DeleteProjectById :exec
DELETE FROM public.project
WHERE
  id = $1
  AND user_id = $2
`

type DeleteProjectByIdParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteProjectById(ctx context.Context, arg DeleteProjectByIdParams) error {
	_, err := q.db.Exec(ctx, deleteProjectById, arg.ID, arg.UserID)
	return err
}

const getAllProjects = `-- name: GetAllProjects :many
SELECT
  id, user_id, name, description, created_at, updated_at
FROM public.project p
WHERE
  p.user_id = $1
ORDER BY
  COALESCE(p.updated_at, p.created_at) DESC
`

func (q *Queries) GetAllProjects(ctx context.Context, userID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getAllProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectById = `-- name: GetProjectById :one
SELECT
  id, user_id, name, description, created_at, updated_at
FROM
  public.project p
WHERE
  p.id = $1
  AND p.user_id = $2
`

type GetProjectByIdParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetProjectById(ctx context.Context, arg GetProjectByIdParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectById, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT
  p.name AS project_name
  ,p.description AS project_description
  ,p.created_at AS project_created_at
  ,p.updated_at AS project_updated_at
  ,COALESCE(
    json_agg(
      DISTINCT jsonb_build_object(
        'deployment_name', d.name,
        'techstack_name', dt.name,
        'container_name', c.name
      )
    ) FILTER (WHERE d.name IS NOT NULL),
    '[]'
  )::jsonb AS deployments
FROM
  public.project p
LEFT JOIN deployment d
	ON d.project_id = p.id
LEFT JOIN deployment_history dh
	ON dh.deployment_id = d.id
		AND dh.is_active IS true
LEFT JOIN deployment_techstack dt
	ON dt.id = dh.deployment_techstack_id
LEFT JOIN container c
	ON c.deployment_history_id = dh.id
WHERE
  p.user_id = $1
  AND p.name ILIKE $2
GROUP BY
  p.name, p.description, p.created_at, p.updated_at
`

type GetProjectByNameParams struct {
	UserID pgtype.UUID
	Name   string
}

type GetProjectByNameRow struct {
	ProjectName        string
	ProjectDescription pgtype.Text
	ProjectCreatedAt   pgtype.Timestamptz
	ProjectUpdatedAt   pgtype.Timestamptz
	Deployments        json.RawMessage
}

func (q *Queries) GetProjectByName(ctx context.Context, arg GetProjectByNameParams) (GetProjectByNameRow, error) {
	row := q.db.QueryRow(ctx, getProjectByName, arg.UserID, arg.Name)
	var i GetProjectByNameRow
	err := row.Scan(
		&i.ProjectName,
		&i.ProjectDescription,
		&i.ProjectCreatedAt,
		&i.ProjectUpdatedAt,
		&i.Deployments,
	)
	return i, err
}

const updateProjectById = `-- name: UpdateProjectById :exec
UPDATE public.project
SET name = $1,
    description = $2,
    updated_at = now()
WHERE
  id = $3
  AND user_id = $4
`

type UpdateProjectByIdParams struct {
	Name        string
	Description pgtype.Text
	ID          pgtype.UUID
	UserID      pgtype.UUID
}

func (q *Queries) UpdateProjectById(ctx context.Context, arg UpdateProjectByIdParams) error {
	_, err := q.db.Exec(ctx, updateProjectById,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.UserID,
	)
	return err
}
